### ISSUE TITLE
License / Citation

### ISSUE THREAD

**Issue by Qix-** [ACskyline/Wave-Particles-with-Interactive-Vortices#1]
Hi, great work here.

Have you imposed a license on the source material or the method? Being able to reference this would be really cool in future projects, but I don't see usage notes anywhere.

**Comment by ACskyline** [comment]
Thanks for asking. This is my first time licensing my own repository. So if there is anything wrong, please tell me.

**Comment by Qix-** [comment]
What you've got now works great :) Awesome stuff by the way. I enjoy reading through all of your work.

**Comment by ACskyline** [comment]
>           What you've got now works great :) Awesome stuff by the way. I enjoy reading through all of your work.

I'm glad you like it. Thanks!
